### ISSUE TITLE
should snapshot manager implement merging a snapshot back into the origin?

### ISSUE THREAD

**Issue by trgill** [snapshotmanager/snapm#4]
I might be missing it, but I don't immediately see support for merging a snapshot back into its origin.

So, in the case of LVM - "lvconvert --merge vg/snapshot_name"

In the ansible role, I called it "revert", but I'm considering dropping it to make sure we are compatible with snapm.

**Comment by bmr-cymru** [comment]
Yes - this is on the TODO list for the MVP. I was also considering using `revert` as the command verb for this functionality so that matches nicely with what you're doing.

I expect to get to this soon after finishing the boot integration work.

**Comment by trgill** [comment]
Thanks for the response.  Ok - great.

Currently I've got:

- snapshot - I think this maps to create in snapm
- check - this validates the set of snapshots has been allocated and properly sized as requsted
- extend - expand the space allocated to the snapshot
- remove - removes the snapshots... maps to delete in snapm
- mount - Swap the origin and the snapshot (or back).  I don't see this in snapm?  
- revert - merge the snapshot back into the source (discussed above)

Do you plan to support mount?  In the role, this just swaps the origin with the snapshot (and back).

I can still make changes, so I'm thinking about changing snapshot to create and remove to delete.  I think is would be nice to use the same commands.

**Comment by bmr-cymru** [comment]
I think this generally all makes sense and I agree it would be good to have the command names sync up. The only thing I'm a bit unclear on is the functionality of the mount operation? How does this work in practice? I'm not clear on what swapping the origin and snapshot means. Can you explain this a bit further?

I was planning to support a mount operation in snapshot manager at some point (and also possibly a chroot command to allow commands to be run against the snapshot set). The idea I had was to mount these at something like `/var/lib/snapm/<snapset_name>/` to allow the snapshot set content to be inspected and interacted with.

**Comment by trgill** [comment]
The mount command is just a way to easily allow the ansible role users to invoke mount/umount on the target system.

LVM supports delaying the activation, but I don't have support for that yet in the ansible role.
