### ISSUE TITLE
Command failed: module 'boom.command' has no attribute 'create_config'

### ISSUE THREAD

**Issue by trgill** [snapshotmanager/snapm#73]
Just updated to the latest and saw:

Installed /usr/local/lib/python3.11/site-packages/snapm-0.3.0-py3.11.egg
Processing dependencies for snapm==0.3.0
Searching for boom-boot==1.6.4
Best match: boom-boot 1.6.4
Processing boom_boot-1.6.4-py3.11.egg
boom-boot 1.6.4 is already the active version in easy-install.pth
Installing boom script to /usr/local/bin

Using /usr/local/lib/python3.11/site-packages/boom_boot-1.6.4-py3.11.egg
Searching for dbus-python==1.3.2
Best match: dbus-python 1.3.2
Adding dbus-python 1.3.2 to easy-install.pth file

Using /usr/lib64/python3.11/site-packages
Finished processing dependencies for snapm==0.3.0

[root@fedora snapm]# snapm snapset create snapm-test /mnt/data_vg1_data1 /mnt/data_vg1_data2 /mnt/data_vg2_data3 /mnt/data_vg2_data4 /mnt/data_vg3_data5 /mnt/data_vg3_data6 /mnt/data_vg3_data7
ERROR - Command failed: module 'boom.command' has no attribute 'create_config'

Sorry if I missed something.  I updated boom and re-installed - then updated snapm and reinstalled?  That right?

**Comment by bmr-cymru** [comment]
That's a bit strange - `boom.command.create_config()` was added in 1.6.4. Is it possible you have an older installation somewhere that's being picked up instead?

I'll try to install this on a fresh system and see if I can reproduce. I'm assuming from the output you're installing with pip?

For what it's worth these are the commits that added `create_config()` leading up to the 1.6.4 tag:

```
commit e2b29e328f97eef28c53279376b4d8ec76520f1b
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Wed Jun 19 17:56:53 2024 +0100

    boom: fix formatting in boom.command.create_config()
    
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>

commit 938a8e4749883ce6ee2973f495cb19643fb181c0 (bmr-default-config)
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Wed Jun 19 17:19:14 2024 +0100

    boom: advise user to run 'boom config create' if no config found
    
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>

commit 9bfc069fe7398071bb9bfd6bb9736fcffdfd1721
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Wed Jun 19 17:10:30 2024 +0100

    boom: add 'boom config create' command
    
    Add a command to create a default boom configuration in /boot if no
    configuration is already present (for e.g. if installing from PyPi via
    pip).
    
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>

```

```
$ git describe --contains e2b29e328f97eef28c53279376b4d8ec76520f1b
1.6.4~4
```

**Comment by bmr-cymru** [comment]
Running `pip install .` from current git main is also working for me:

```
root@localhost:~/src/git# git clone https://github.com/snapshotmanager/boom-boot
Cloning into 'boom-boot'...
remote: Enumerating objects: 5173, done.
remote: Counting objects: 100% (1080/1080), done.
remote: Compressing objects: 100% (363/363), done.
remote: Total 5173 (delta 708), reused 1031 (delta 667), pack-reused 4093
Receiving objects: 100% (5173/5173), 1.06 MiB | 5.56 MiB/s, done.
Resolving deltas: 100% (3621/3621), done.
root@localhost:~/src/git# git clone https://github.com/snapshotmanager/snapm
Cloning into 'snapm'...
remote: Enumerating objects: 1317, done.
remote: Counting objects: 100% (796/796), done.
remote: Compressing objects: 100% (292/292), done.
remote: Total 1317 (delta 541), reused 710 (delta 485), pack-reused 521
Receiving objects: 100% (1317/1317), 351.26 KiB | 5.17 MiB/s, done.
Resolving deltas: 100% (827/827), done.
root@localhost:~/src/git# cd boom-boot/
root@localhost:~/src/git/boom-boot# pip install .
Processing /root/src/git/boom-boot
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: dbus-python>=1.2.16 in /usr/lib64/python3.12/site-packages (from boom_boot==1.6.4) (1.3.2)
Building wheels for collected packages: boom_boot
  Building wheel for boom_boot (pyproject.toml) ... done
  Created wheel for boom_boot: filename=boom_boot-1.6.4-py3-none-any.whl size=128638 sha256=54f92f9ea100ba3425277ccfcd21a782e5fa12a50c8cf7a105982305289c9714
  Stored in directory: /root/.cache/pip/wheels/2a/91/11/f50997d193fd57480fcd167182aafd5ff6204e7ba5b5719ccb
Successfully built boom_boot
Installing collected packages: boom_boot
Successfully installed boom_boot-1.6.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@localhost:~/src/git/boom-boot# cd ../snapm/
root@localhost:~/src/git/snapm# pip install .
Processing /root/src/git/snapm
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: boom-boot>=1.6.4 in /usr/local/lib/python3.12/site-packages (from snapm==0.3.0) (1.6.4)
Requirement already satisfied: dbus-python>=1.2.16 in /usr/lib64/python3.12/site-packages (from boom-boot>=1.6.4->snapm==0.3.0) (1.3.2)
Building wheels for collected packages: snapm
  Building wheel for snapm (pyproject.toml) ... done
  Created wheel for snapm: filename=snapm-0.3.0-py3-none-any.whl size=69841 sha256=21c43f81c19913f159798a3f931a16279b538c63e5ee0af405565feca5d1256a
  Stored in directory: /tmp/pip-ephem-wheel-cache-93njfcbv/wheels/31/6a/bb/79b543960c02a7cdd5361725a585f2e3a46f543bff7c24bb16
Successfully built snapm
Installing collected packages: snapm
Successfully installed snapm-0.3.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@localhost:~/src/git/snapm# snapm snapset list
SnapsetName  Time                 NrSnapshots Status  MountPoints             
test         2024-07-12 16:35:45            3 Active  /, /home, /var
```

**Comment by bmr-cymru** [comment]
What do you get running the following commands in the python shell?

```python
Python 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 14.0.1 20240217 (Red Hat 14.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boom
>>> boom.__version__
'1.6.4'
>>> import sys
>>> sys.path
['', '/usr/lib64/python312.zip', '/usr/lib64/python3.12', '/usr/lib64/python3.12/lib-dynload', '/usr/local/lib/python3.12/site-packages', '/usr/lib64/python3.12/site-packages', '/usr/lib/python3.12/site-packages']

```

**Comment by trgill** [comment]
I've had a few versions installed.  Let me take some time to clean up and make sure I haven't done anything that is causing the problem.

[root@fedora tgill]# python
Python 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boom
>>> boom.__version__
'1.6.3'
>>> import sys
>>> sys.path
['', '/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/root/.local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/site-packages/boom-1.6.3-py3.11.egg', '/usr/local/lib/python3.11/site-packages/snapm-0.3.0-py3.11.egg', '/usr/local/lib/python3.11/site-packages/boom_boot-1.6.4-py3.11.egg', '/usr/lib64/python3.11/site-packages', '/usr/lib/python3.11/site-packages']
>>>

**Comment by bmr-cymru** [comment]
> > > > import boom
> > > > boom.**version**
> > > > '1.6.3'
> > > > import sys
> > > > sys.path
> > > > ['', '/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/root/.local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/site-packages/boom-1.6.3-py3.11.egg', '/usr/local/lib/python3.11/site-packages/snapm-0.3.0-py3.11.egg', '/usr/local/lib/python3.11/site-packages/boom_boot-1.6.4-py3.11.egg', '/usr/lib64/python3.11/site-packages', '/usr/lib/python3.11/site-packages']

Looks like `/usr/local/lib/python3.11/site-packages/boom-1.6.3-py3.11.egg'` is taking precedence over `/usr/local/lib/python3.11/site-packages/boom_boot-1.6.4-py3.11.egg`.

**Comment by trgill** [comment]
thanks
