### ISSUE TITLE
Support size policy hints for snapshot plugins that use a fixed snapshot size

### ISSUE THREAD

**Issue by bmr-cymru** [snapshotmanager/snapm#9]
It should be possible for the user to control the amount of space allocated to snapshots created by plugins that a fixed size for the snapshot data store (i.e. dm-snapshot).

This should support various options for specifying the size on a per-mount point basis

* Fixed size
* % free space
* % space used on the origin
* % size of the origin

In addition a global `--size-policy` option should allow this to be set for all snapshots in a set.

**Comment by trgill** [comment]
FYI - I'll mirror these options in the snapshot role.

**Comment by bmr-cymru** [comment]
Fixed in #20
